# Generated by Django 4.0.5 on 2022-07-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='access_granted',
            field=models.BooleanField(default=False),
        ),
    ]
