# Generated by Django 4.0.5 on 2022-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
