# Generated by Django 4.0.5 on 2022-07-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_alter_room_room_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=150)),
                ('card_num', models.CharField(max_length=50)),
                ('card_cvv', models.CharField(max_length=10)),
                ('card_expiry', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reserve_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('Num_of_persons', models.IntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.room')),
            ],
        ),
    ]
