# Generated by Django 4.0.5 on 2022-07-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0006_checkins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('Num_of_persons', models.IntegerField()),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('billing_date', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.room')),
            ],
        ),
    ]
