# Generated by Django 4.0.5 on 2022-07-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0007_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='Num_of_persons',
        ),
    ]
