# Generated by Django 4.0.5 on 2022-07-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0008_remove_billing_num_of_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billing_date',
            field=models.DateField(),
        ),
    ]
